# Generated by Django 5.0.4 on 2024-04-12 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urusoro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_personne', to='urusoro.personne'),
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaire_personne', to='urusoro.personne')),
            ],
        ),
    ]
