# Generated by Django 5.0.4 on 2024-04-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urusoro', '0002_alter_presence_personne_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='montant',
            field=models.IntegerField(editable=False),
        ),
    ]
